[[profile]]
name = "home-office"
exec = [
  "notify-send shikane \"Display Profile $SHIKANE_PROFILE_NAME has been applied\"",
]

[[profile.output]]
enable = true
search = ["m=0x094C", "s=", "v=BOE"]
mode = "1920x1200@60.003Hz"
position = "0,1363"
scale = 1.69921875
transform = "normal"
adaptive_sync = false
[[profile.output]]

enable = true
search = ["m=DELL U3417W", "s=660X88270TTL", "v=Dell Inc."]
mode = "3440x1440@59.973Hz"
position = "1400,799"
scale = 1.30078125
transform = "normal"
adaptive_sync = false
exec = ["~/.config/sway/bin/move-workspace-to-output.sh $SHIKANE_OUTPUT_NAME"]

[[profile]]
name = "unplugged"
exec = [
  "notify-send shikane \"Display Profile $SHIKANE_PROFILE_NAME has been applied\"",
]

[[profile.output]]
exec = ["~/.config/sway/bin/move-workspace-to-output.sh $SHIKANE_OUTPUT_NAME"]
enable = true
search = ["m=0x094C", "s=", "v=BOE"]
mode = "1920x1200@60.003Hz"
position = "0,0"
scale = 1.5
transform = "normal"
adaptive_sync = false

[[profile]]
name = "studio"
exec = [
  "notify-send shikane \"Display Profile $SHIKANE_PROFILE_NAME has been applied\"",
]

[[profile.output]]
enable = true
search = ["m=LG HDR 4K", "s=107NTVSDV879", "v=LG Electronics"]
mode = "3840x2160@59.997Hz"
position = "0,0"
scale = 1.5
transform = "normal"
adaptive_sync = false
exec = ["~/.config/sway/bin/move-workspace-to-output.sh $SHIKANE_OUTPUT_NAME"]

[[profile.output]]
enable = true
search = ["m=0x094C", "s=", "v=BOE"]
mode = "1920x1200@60.003Hz"
position = "2560,553"
scale = 1.69921875
transform = "normal"
adaptive_sync = false
